### ISSUE TITLE
panic: runtime error: slice bounds out of range [:4] with length 0

### ISSUE THREAD

**Issue by dr-boss** [StephanGR/gobox#8]
After start script on linux or windows I have message "panic: runtime error: slice bounds out of range [:4] with length 0", Orange PL Funbox6

**Comment by Stoufiler** [comment]
Hello, 

Could you please share the output of the console ?
I've tested it and it worked well

**Comment by dr-boss** [comment]
This is from Windows, but I have same from ubuntu.
Funbox6 Orange PL

```
PS D:\ubnt_bck> .\GO-BOX.exe --ip 192.168.1.1 --box funbox
Password : Can not unmarshal JSON

✅ Successfully connected to Livebox ! ✅
PPPoE Username :
VLAN ID : 0
panic: runtime error: slice bounds out of range [:4] with length 0

goroutine 1 [running]:
main.displayFunboxValues({0xc0000120c0?, 0xc00000a018?})
        /Users/stouf/Documents/Developpement/gobox/functions.go:62 +0x925
main.instantiateFunboxConnection({0xc0000120c0, 0xb}, {0x7ecbbd?, 0x1?}, {0xc00014fb68?, 0xab54e0?})
        /Users/stouf/Documents/Developpement/gobox/main.go:175 +0x4ba
main.main.func2(0xc000114160?)
        /Users/stouf/Documents/Developpement/gobox/main.go:72 +0x20e
github.com/urfave/cli/v2.(*Command).Run(0xc000114160, 0xc000024540, {0xc00007e000, 0x5, 0x8})
        /Users/stouf/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/command.go:274 +0x9eb
github.com/urfave/cli/v2.(*App).RunContext(0xc000112000, {0x893b08?, 0xc000012110}, {0xc00007e000, 0x5, 0x8})
        /Users/stouf/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/app.go:332 +0x616
github.com/urfave/cli/v2.(*App).Run(...)
        /Users/stouf/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/app.go:309
main.main()
        /Users/stouf/Documents/Developpement/gobox/main.go:78 +0x249
```

**Comment by Valdri** [comment]
I have the same error with funbox6

**Comment by Wepted** [comment]
I have the same error with funbox3, on linux
